### ISSUE TITLE
Failed to start actinia-user: 1 (actinia-core:1.0.0)

### ISSUE THREAD

**Issue by pesekon2** [mundialis/actinia_core#225]
The current docker image ends in a failure for me. Is that just me? 

In:

```
docker pull mundialis/actinia-core:1.0.0
docker run --rm mundialis/actinia-core:1.0.0
```

Out:

```
cp: cannot stat '/mnt/pgpass/.pgpass': No such file or directory
chmod: cannot access '/root/.pgpass': No such file or directory
cp: cannot stat '/mnt/pgpass/.grass7': No such file or directory
chmod: cannot access '/root/.grass7/dblogin': No such file or directory
cp: cannot stat '/root/.grass7/dblogin': No such file or directory
Starting GRASS GIS...
Creating new GRASS GIS location <utm32n>...
Cleaning up temporary files...
Cleaning up temporary files...
Starting GRASS GIS...
Creating new GRASS GIS location <latlong_wgs84>...
Cleaning up temporary files...
Cleaning up temporary files...
Starting GRASS GIS...
Creating new GRASS GIS location <nc_spm_08>...
Cleaning up temporary files...
Cleaning up temporary files...
Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 30, in <module>
    from actinia_core.core.user import ActiniaUser
ModuleNotFoundError: No module named 'actinia_core.core.user'
Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 30, in <module>
    from actinia_core.core.user import ActiniaUser
ModuleNotFoundError: No module named 'actinia_core.core.user'
Failed to start actinia-user: 1
```

**Comment by neteler** [comment]
I can confirm the problem, also with

```
docker pull mundialis/actinia-core:1.0.1
docker run --rm mundialis/actinia-core:1.0.1
```

**Comment by griembauer** [comment]
Hi @pesekon2 ,
thanks for noticing, there are two issues here: 
### 1
```

Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 30, in <module>
    from actinia_core.core.user import ActiniaUser
ModuleNotFoundError: No module named 'actinia_core.core.user'
Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 30, in <module>
    from actinia_core.core.user import ActiniaUser
ModuleNotFoundError: No module named 'actinia_core.core.user'
```
This has been fixed in v1.0.1 (path to python modules for import was wrong)

### 2
actinia requires a running redis database, so starting only the actinia-container with `docker run...` will only work if there is a local redis database running and the connection is configured in the `actinia.cfg` (for example https://github.com/mundialis/actinia_core/blob/main/docker/actinia-core-alpine/actinia.cfg). 
The easier way to start both actinia and redis is to use `docker-compose`, e.g. navigate to the `actinia_core/docker` directory and run
```
docker-compose -f docker-compose.yml build  # you can also specify the desired actinia version in the docker-compose.yml

docker-compose -f docker-compose.yml up 
# or in detached mode:
docker-compose -f docker-compose.yml up -d

```

**Comment by pesekon2** [comment]
> Hi @pesekon2 ,
> thanks for noticing, there are two issues here:
> ### 1
> 
> ```
> 
> Traceback (most recent call last):
>   File "/usr/bin/actinia-user", line 30, in <module>
>     from actinia_core.core.user import ActiniaUser
> ModuleNotFoundError: No module named 'actinia_core.core.user'
> Traceback (most recent call last):
>   File "/usr/bin/actinia-user", line 30, in <module>
>     from actinia_core.core.user import ActiniaUser
> ModuleNotFoundError: No module named 'actinia_core.core.user'
> ```
> 
> This has been fixed in v1.0.1 (path to python modules for import was wrong)
> ### 2
> 
> actinia requires a running redis database, so starting only the actinia-container with `docker run...` will only work if there is a local redis database running and the connection is configured in the `actinia.cfg` (for example https://github.com/mundialis/actinia_core/blob/main/docker/actinia-core-alpine/actinia.cfg).
> The easier way to start both actinia and redis is to use `docker-compose`, e.g. navigate to the `actinia_core/docker` directory and run
> 
> ```
> docker-compose -f docker-compose.yml build  # you can also specify the desired actinia version in the docker-compose.yml
> 
> docker-compose -f docker-compose.yml up 
> # or in detached mode:
> docker-compose -f docker-compose.yml up -d
> ```

**Comment by pesekon2** [comment]
(sorry for closing and re-opening few minutes ago. I have clicked on a wrong button)

> Traceback (most recent call last):
>   File "/usr/bin/actinia-user", line 30, in <module>
>     from actinia_core.core.user import ActiniaUser
> ModuleNotFoundError: No module named 'actinia_core.core.user'
> Traceback (most recent call last):
>   File "/usr/bin/actinia-user", line 30, in <module>
>     from actinia_core.core.user import ActiniaUser
> ModuleNotFoundError: No module named 'actinia_core.core.user'
> ```
> 
> This has been fixed in v1.0.1 (path to python modules for import was wrong)

True. I should have checked this before running it. My fault, thanks.

However, now I get the following:

In:

```
docker pull mundialis/actinia-core:1.0.1
docker run --rm mundialis/actinia-core:1.0.1
```

Out:

```
cp: cannot stat '/mnt/pgpass/.pgpass': No such file or directory
chmod: cannot access '/root/.pgpass': No such file or directory
cp: cannot stat '/mnt/pgpass/.grass7': No such file or directory
chmod: cannot access '/root/.grass7/dblogin': No such file or directory
cp: cannot stat '/root/.grass7/dblogin': No such file or directory
Starting GRASS GIS...
Creating new GRASS GIS location <utm32n>...
Cleaning up temporary files...
Cleaning up temporary files...
Starting GRASS GIS...
Creating new GRASS GIS location <latlong_wgs84>...
Cleaning up temporary files...
Cleaning up temporary files...
Starting GRASS GIS...
Creating new GRASS GIS location <nc_spm_08>...
Cleaning up temporary files...
Cleaning up temporary files...
[2021-06-26 09:26:24,932] ERROR     : actinia-core.redis_base -Error -2 connecting to redis:6379. Name does not resolve. [in /usr/lib/python3.8/site-packages/actinia_core/core/common/redis_base.py:71]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
sock = self._connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket
.
gaierror
:
[Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 312, in <module>
main()
  File "/usr/bin/actinia-user", line 222, in main
if user.exists() == 1:
  File "/usr/lib/python3.8/site-packages/actinia_core/core/common/user.py", line 379, in exists
return self.db.exists(self.user_id)
  File "/usr/lib/python3.8/site-packages/actinia_core/core/redis_user.py", line 230, in exists
return self.redis_server.exists(self.user_id_hash_prefix + user_id)
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 1581, in exists
return self.execute_command('EXISTS', *names)
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
connection.connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions
.
ConnectionError
:
Error -2 connecting to redis:6379. Name does not resolve.
[2021-06-26 09:26:25,216] ERROR     : actinia-core.redis_base -Error -2 connecting to redis:6379. Name does not resolve. [in /usr/lib/python3.8/site-packages/actinia_core/core/common/redis_base.py:71]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
sock = self._connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket
.
gaierror
:
[Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/actinia-user", line 312, in <module>
main()
  File "/usr/bin/actinia-user", line 246, in main
if user.exists() == 0:
  File "/usr/lib/python3.8/site-packages/actinia_core/core/common/user.py", line 379, in exists
return self.db.exists(self.user_id)
  File "/usr/lib/python3.8/site-packages/actinia_core/core/redis_user.py", line 230, in exists
return self.redis_server.exists(self.user_id_hash_prefix + user_id)
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 1581, in exists
return self.execute_command('EXISTS', *names)
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
connection.connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions
.
ConnectionError
:
Error -2 connecting to redis:6379. Name does not resolve.
Failed to start actinia-user: 1
```

(shall I move this to another issue as it is connected to 1.0.1 and not 1.0.0?)

> ### 2
> 
> actinia requires a running redis database, so starting only the actinia-container with `docker run...` will only work if there is a local redis database running and the connection is configured in the `actinia.cfg` (for example https://github.com/mundialis/actinia_core/blob/main/docker/actinia-core-alpine/actinia.cfg).
> The easier way to start both actinia and redis is to use `docker-compose`, e.g. navigate to the `actinia_core/docker` directory and run
> 
> ```
> docker-compose -f docker-compose.yml build  # you can also specify the desired actinia version in the docker-compose.yml
> 
> docker-compose -f docker-compose.yml up 
> # or in detached mode:
> docker-compose -f docker-compose.yml up -d
> ```

Yes, I used to solve that by a docker-compose, but I was trying to produce one image as simple as possible - just a core image with some extra addons installed. However, the new issue happens also when using docker-compose.

**Comment by griembauer** [comment]
Hi @pesekon2,
when you use `docker run --rm mundialis/actinia-core:1.0.1`, the container will execute a start-script, e.g. https://github.com/mundialis/actinia_core/blob/main/docker/actinia-core-alpine/start.sh, copying e.g. the `.pgpass` file and eventually starting actinia. actinia will then look for the `redis`-connection and will fail if there is none, explaining the errors in part 1 of your output. However, using `docker-compose` should solve the issue by automatically launching a `redis`-container as well. Could you let us know the exact commands and outputs you used with `docker-compose`?

**Comment by pesekon2** [comment]
> However, using `docker-compose` should solve the issue by automatically launching a `redis`-container as well. Could you let us know the exact commands and outputs you used with `docker-compose`?

(sorry for the delay. I was offline for two weeks)

My `docker-compose` looks like this:

```
version: "3"
services:

  actinia-core:
    build:
      context: ..
      dockerfile: actinia/Dockerfile
    volumes:
      - ./actinia-core-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-core-data/userdata:/actinia_core/userdata
    ports:
      - "8088:8088"
    depends_on:
      - redis

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      ',
      'tail -F anything'
    ]
    ports:
        - "6379:6379"
```

The reason for `context: ..` is that I want to copy some data later from a directory above within a Dockerfile, but so far my Dockerfile contains only this line: `FROM mundialis/actinia-core:1.0.1` (making it an exact copy of the 1.0.1 image)

**Comment by mmacata** [comment]
Hi pesekon2,

I can confirm - actinia is not able to run without a running redis database.

What is the exact error on startup? The above error `Error -2 connecting to redis:6379. Name does not resolve.` usually means that there is no redis database running in the same (docker-) network as actinia, where `redis` would be the service name under which actinia can reach it. 
Another reason (and slightly different error message) could be that the docker mount of redis credentials file was not successful. It must be located relative to the docker-compose file at `redis_data/config/.redis` and contains the password (default: `pass`) which must be the same as in the actinia config (which is with the `mundialis/actinia-core:1.0.1` image `pass` by default as well). 

You can have a look at the docker-compose-dev.yml in the repository which also contains the build stage. From within the actinia repo, you can run 

```
docker-compose -f docker/docker-compose-dev.yml build
docker-compose -f docker/docker-compose-dev.yml up
```
and it should start without errors.

**Comment by pesekon2** [comment]
I got it. The last issue I had was caused by `redis_data`. The directory was created by `docker_compose`, and therefore it was empty; as I have seen it, I thought that I have created it by myself and it contained all the necessary files. 

Closing this issue with the lesson learned: If getting `connecting to redis:6379. Name does not resolve`, check the `redis_data` directory (a single typo in one of the files could end in the same situation).
